### ISSUE TITLE
Installing plugin

### ISSUE THREAD

**Issue by tomsej** [sasakitoa/embulk-input-kafka#1]
Hi, could you please write me how to install this plugin to Embulk? When I run `embulk gem install embulk-input-kafka` it doesn't work.

**Comment by sasakitoa** [comment]
Hi.
As you said, you can't install this plugin with `embulk gem install embulk-install-kafka` because I don't release this plugin to RubyGems.org.
Please try to run `embulk gem install --local pkg/embulk-input-kafka-0.2.0.gem` after build.

**Comment by tomsej** [comment]
Thank you! And are you going to release it?
