### ISSUE TITLE
Support security SSL transport layer

### ISSUE THREAD

**Issue by javier-sanz** [sasakitoa/embulk-input-kafka#6]
The default kafka client this plugin is using supports SSL security transport layer. [Here](https://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.6.2/bk_security/content/ch_wire-kafka.html) explain how. Could those parameters be exposed on the plugin configuration?

**Comment by sasakitoa** [comment]
Thank you for comment, @javier-sanz .
We can specify `extra_kafka_options` for KafkaConsumer used in this plugin.
Please try to specify also SSL options in this section such below.

    in:
      type: kafka
    (snip)
      extra_kafka_options:
        security.protocol = SSL
        ssl.truststore.location = /var/private/ssl/kafka.client.truststore.jks
        ssl.truststore.password = test1234

**Comment by javier-sanz** [comment]
@sasakitoa Thanks to you for your answer.

That did work indeed. I did not think about this option when I initially read your documentation.
